version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 15
  target-branch: master
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  labels:
    - 'dependencies'
# maintaining v2
- package_manager: "java:gradle"
  target_branch: "release/2.x.x"
  directory: "/"
  update_schedule: "weekly"
  default_labels:
    - "dependencies"
    - "release-2.x.x"
  commit_message:
    prefix: "fix"
    prefix_development: "chore"
    include_scope: true
- package_manager: "github_actions"
  target_branch: "release/2.x.x"
  directory: "/"
  update_schedule: "monthly"
  default_labels:
    - "dependencies"
    - "release-2.x.x"
  commit_message:
    prefix: "chore"
    prefix_development: "chore"
    include_scope: true
