version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 15
  target-branch: master
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  labels:
    - 'dependencies'
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
    - "dependencies"
  commit-message:
    prefix: "chore"
    prefix-development: "chore"
    include: scope
# maintaining v2
- package-ecosystem: gradle
  target-branch: "release/2.x.x"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
    - "dependencies"
    - "release-2.x.x"
  commit-message:
    prefix: "fix"
    prefix-development: "chore"
    include: scope
- package-ecosystem: github-actions
  target-branch: "release/2.x.x"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
    - "dependencies"
    - "release-2.x.x"
  commit-message:
    prefix: "chore"
    prefix-development: "chore"
    include: scope
