# configure the semantic-release utility
tagFormat: ${version}
debug: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
branches:
  - name: 'main'
  - name: 'release/8.x.x'
    range: '8.x'
