server:
  applicationConnectors:
  - type: http
    port: 0
  adminConnectors:
  - type: http
    port: 0

cors:
  allowedHeaders:
    - some
  exposedHeaders:
    - exposed
  allowedOrigins:
    - "*"
