version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
 
