server:
  applicationConnectors:
  - type: http
    port: 0
  adminConnectors:
  - type: http
    port: 0

kafka:
  brokers: ${BROKER_CONNECTION_STRING:-[]}
  topics:
    example0:
      name: exampleTopic
    example1:
      name: exampleTopicConfiguration
      partitions: 2
      replicationFactor: 2
      config:
        max.message.bytes: 1024
