kafka:
  brokers:
    - server: localhost
      port: 9091
  consumers:
    consumer1:
      config:
        key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
        value.deserializer: org.apache.kafka.common.serialization.LongDeserializer
    consumer2:
  producers:
    producer1:
      config:
        key.serializer: org.apache.kafka.common.serialization.LongSerializer
        value.serializer: org.apache.kafka.common.serialization.LongSerializer
    producer2:
  listenerConfig:
    async:
      commitType: ASYNC
      useAutoCommitOnly: false
      instances: 1
      topicMissingRetryMs: 60000
  topics:
    topicId1:
      name: topic1
      partitions: 2
      replicationFactor: 2
      config:
        max.message.bytes: 1024
        retention.ms: 60480000
    topicId2:
      name: topic2
      partitions: 1
      replicationFactor: 1
