server:
  applicationConnectors:
  - type: http
    port: 0
  adminConnectors:
  - type: http
    port: 0

kafka:
  adminConfig:
    adminClientrequestTimeoutMs: 2000
  brokers: ${BROKER_CONNECTION_STRING}
  consumers:
    consumer1:
      config:
        key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
        value.deserializer: org.apache.kafka.common.serialization.LongDeserializer
    consumer2:
  producers:
    producer1:
      config:
        key.serializer: org.apache.kafka.common.serialization.LongSerializer
        value.serializer: org.apache.kafka.common.serialization.LongSerializer
    producer2:
    producer3:
      config:
        key.serializer: org.apache.kafka.common.serialization.LongSerializer
        value.serializer: KafkaJsonSerializer

  listenerConfig:
    async:
      commitType: ASYNC
      useAutoCommitOnly: false
      instances: 1
      topicMissingRetryMs: 60000
  topics:
    topicId1:
      name: topic1
      partitions: 2
      replicationFactor: 2
      config:
        max.message.bytes: 1024
        retention.ms: 60480000
    topicId2:
      name: topic2
      partitions: 1
      replicationFactor: 1
