# This workflow builds, tests, and releases the modules.
name: Java CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # build library
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        java_version: ['1.8', '11']
        os: ['ubuntu-latest', 'windows-latest']

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}

      - name: Test with Gradle
        run: ./gradlew --parallel --continue check

      - name: Generate Test Report
        if: always()
        run: ./gradlew -x test testReport

      # TODO: add retention policy when it is supported (https://github.com/actions/upload-artifact/issues/34)
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: ${{ matrix.os }}-${{ matrix.java_version }}-test-results
          path: build/reports/allTests

      - name: Sonarcloud
        # do not execute for PRs that origin from forks since we are missing the secrets for the scan
        if: "always() && matrix.java_version == '1.8' && matrix.os == 'ubuntu-latest' && !(github.event.pull_request && github.event.pull_request.head.repo.fork)"
        run: ./gradlew -x test codeCoverageReport sonarqube
        env:
          SONAR_LOGIN_TOKEN: ${{ secrets.SONAR_LOGIN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR: ${{ github.event.number }}

  # create release and publish the artifacts
  semantic-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Semantic release
        run: |
          sudo npm install -g \
            semantic-release@15.13.31 \
            @semantic-release/git@7.0.18 \
            @semantic-release/release-notes-generator@7.3.5 \
            @semantic-release/exec@3.3.8 \
            @semantic-release/github@5.5.6

      - name: Release and Publish
        run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SDA_NEXUS_USER: ${{ secrets.NEXUS_LOGIN_USER }}
          SDA_NEXUS_PASSWORD: ${{ secrets.NEXUS_LOGIN_PASSWORD }}
