name: Issue Notification Workflow
on:
  issues:
    types:
      - opened
jobs:
  notificate_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action data to a Slack workflow
        uses: slackapi/slack-github-action@0d95c9a7becc1e6e297d76df9bc735c44f4cbcbc # v3.0.5
        with:
          payload-delimiter: "_"
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
