name: Issue Notification Workflow
on:
  issues:
    types:
      - opened
jobs:
  notificate_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action data to a Slack workflow
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        with:
          payload-delimiter: "_"
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
