# This workflow tests a regression that came with a Kafka client update in apps running distroless
# images with read only file system.
# See sda-commons-server-kafka/src/test/DockerTest for details
name: Read only file system

on:
  pull_request:

jobs:
  test-in-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: build image
        run: docker build -t kafka-ro:test .
      - name: Run writable # should always pass
        run: docker run kafka-ro:test
      - name: Run readonly # should fail with wrong kafka-client version
        run: docker run --read-only kafka-ro:test
