name: Temporary CI Proxy

on:
  pull_request:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 1
      - name: Test with Gradle in Docker
        run: ./proxy-docker-test.sh
